/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/nousresearch/agent_harness-go/export */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "agent_harness.go"



#include <stdlib.h>
#include <text_engine.h>
#include <agent_harness_arch.h>
#include <mem_pool.h>

// Extra Go-side utilities (pure Go, no C dependency)
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* AgentHarnessGoVersion(void);
extern int AgentHarnessHealthCheck(void);
extern long long AgentHarnessTextSearchBMH(char* haystack, size_t hlen, char* needle, size_t nlen);
extern long long AgentHarnessTextSearchBMHReverse(char* haystack, size_t hlen, char* needle, size_t nlen);
extern int AgentHarnessTextCount(char* haystack, size_t hlen, char* needle, size_t nlen);
extern size_t AgentHarnessStrLower(char* str, size_t len);
extern size_t AgentHarnessStrUpper(char* str, size_t len);
extern size_t AgentHarnessStrTrim(char* str, size_t len);
extern int AgentHarnessGlobMatch(char* pattern, char* str);
extern int AgentHarnessGlobMatchCI(char* pattern, char* str);
extern int AgentHarnessUtf8Valid(char* str, size_t len);
extern int AgentHarnessUtf8Codepoints(char* str, size_t len);
extern size_t AgentHarnessSlugify(char* input, size_t inLen, char* outBuf, size_t outCap);
extern size_t AgentHarnessTruncate(char* input, size_t inLen, size_t maxLen, char* suffix, size_t sufLen, char* outBuf, size_t outCap);
extern size_t AgentHarnessWordFreqHash(char* input, size_t inLen, int topN, char* outBuf, size_t outCap);
extern size_t AgentHarnessNormalizeWS(char* input, size_t inLen, int lineEnding, char* outBuf, size_t outCap);
extern int AgentHarnessBaseConvert(char* number, int baseFr, int baseTo, char* outBuf, size_t outCap);
extern int AgentHarnessExtractURLs(char* input, size_t inLen, char* outBuf, size_t outCap, int maxUrls);
extern int AgentHarnessExtractEmails(char* input, size_t inLen, char* outBuf, size_t outCap, int maxEmails);
extern int AgentHarnessExtractHashtags(char* input, size_t inLen, char* outBuf, size_t outCap, int maxTags);

/* Return type for AgentHarnessArenaStats */
struct AgentHarnessArenaStats_return {
	int r0; /* total */
	int r1; /* used */
	int r2; /* blocks */
};
extern struct AgentHarnessArenaStats_return AgentHarnessArenaStats(GoUint64 arenaPtr);
extern void AgentHarnessFree(void* ptr);

#ifdef __cplusplus
}
#endif
